apiVersion: v1
kind: Pod
metadata: 
  name: service-pod
  labels:
    app: service-pod
    env: dev
spec:
  containers:
  - name: test-service
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-pod
spec:
  selector:
    app: service-pod
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
