apiVersion: v1
kind: Pod
metadata:
  name:label-demo
  labels:
    course: DevOps
    Traniner: "Praveen"
spec:
  #list of container
  container:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80