apiVersion: v1
kind: Pod
metadata: 
  name: configpod
spec: 
  containers:
  - name: configpod
    image: nginx
    ports:
      - containerPort: 80
    env:
      - name: AUTHOR
        valueFrom:
          configMapKeyRef:
            name: devops-config
            key: author
      - name: EDITOR
        valueFrom:
          configMapKeyRef:
            name: devops-config
            key: Editor
---
apiVersion: v1
kind: Pod
metadata: 
  name: configpod-1
spec: 
  containers:
  - name: configpod-1
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: devops-config