apiVersion: v1
kind: Pod
metadata: 
  name: configpod-1
spec: 
  containers:
  - name: configpod-1
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: devops-secret